package Principal;
public enum TiposToken {
    // PALAVRAS CHAVE
    IF, ELSE, WHILE, FOR, DO,
    RETURN, BREAK, CLASS,

    //FUNCOES
    PRINT,
    
    // DELIMITADORES
    PAREN_L, PAREN_R, BRACE_L, BRACE_R, BRACKET_L, BRACKET_R, SEMICOLON, COMMA, DOUBLE_DOT,
    
    // IDENTIFICADORES E LITERAIS
    VAR_INT, VAR_BOOL, VAR_FLOAT, VAR_CHAR, IDENTIFIER, FLOAT, INTEGER, CHAR,
    BOOLEAN,

    // CONDICIONAIS
    EQUALS, NOT_EQUAL, GREATER_THAN, LESS_THAN, GREATER_EQUAL, LESS_EQUAL,

    // ATRIBUICAO
    EQUAL,
    
    // OPERADORES
    PLUS, MINUS, TIMES, DIVIDE,

    
    //FIM
    EOF
}